// <auto-generated />
using System;
using LMS.DALL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LMS.DALL.Migrations
{
    [DbContext(typeof(LMSContext))]
    partial class LMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LMS.DOMAIN.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("dateTime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            DateOfBirth = new DateTime(1999, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mar@yah.com",
                            FirstName = "Marlon",
                            LastName = "Elpedes",
                            PhoneNumber = "06666666666"
                        },
                        new
                        {
                            UserId = 2L,
                            DateOfBirth = new DateTime(1989, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jess@yah.com",
                            FirstName = "Jess",
                            LastName = "Allen",
                            PhoneNumber = "02346666666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
